### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dimaslanjaka** [constanzaccg/thesaurus-js#1]
please update the thesaurus engine

**Comment by constanzaccg** [comment]
Hello @dimaslanjaka! Sorry for the delay, in version 1.0.5 it's fixed 😄

**Comment by dimaslanjaka** [comment]
> Hello @dimaslanjaka! Sorry for the delay, in version 1.0.5 it's fixed 😄

thank you, i will report when got errors again.
